title: Laela Baugh
#logo:
description: Aspiring data analyst documenting my learning journey in data and tech. My current toolkit includes SQL and Power BI, with Python next on the roadmap. Committed to continuous growth in the ever-evolving data and tech space, and preparing to further develop my skills through a future masterâ€™s degree alongside seasoned professionals.
show_downloads: True
theme: jekyll-theme-minimal
