title: Laela Baugh
logo: /images/IMG_8207 3.jpg
description: <p>Growth-oriented and business-minded analyst with over 2 years of proven success driving business growth and improving workflows. Track record of maintaining data integrity and solving systemic issues.</p> <p>ðŸ”— [LinkedIn Profile] (https://www.linkedin.com/in/laelabaugh/)</p>
#show_downloads: True
theme: jekyll-theme-minimal
