title: Laela Baugh
logo: /images/IMG_8207 2.jpg
description: Detail-oriented, analytical professional with over 2 years of proven success driving business growth and improving workflows. Background in market research, high-volume project coordination, and quality assurance, with track record maintaining data integrity and solving systemic issues. My projects reflect an ability to define metrics, translate business problems into clear narratives, and convert complex data into actionable insights. 
#show_downloads: True
theme: jekyll-theme-minimal
