title: Laela Baugh
logo: /images/IMG_8207 5.jpg
description: Growth-oriented and business-minded analyst with over 2 years of proven success driving business growth and improving workflows. Track record of maintaining data integrity and solving systemic issues.
#show_downloads: True
theme: jekyll-theme-minimal
